package gui;

import algorithms.Algorithm;

import javax.swing.*;
import java.awt.*;

/**
 * Draws the actual image, generated by the algorithm.
 */
public class DrawPanel extends JPanel {

    @Override
    public void paintComponent(Graphics g){
        //g.clearRect(0,0,getWidth(),getHeight());
        g.drawImage(Algorithm.IMG,0,0,null);
    }

}
